spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #mysql连接配置
    url: jdbc:mysql://mysql.lilian.com:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: mongo.lilian.com  #mongoDB 连接配置
      port: 27030
      database: xingli_hchdb
      username: xingli
      password: xingli
  redis:
    database: 6   # Redis数据库索引（默认为0）
    host: redis.lilian.com  # Redis服务器地址
    port: 7481  # Redis服务器连接端口
    password:    # Redis服务器连接密码（默认为空）
    timeout: 0  # 连接超时时间（毫秒）
    pool:
      max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接
  redis2:
    database: 6   # Redis数据库索引（默认为0）
    host: redis.lilian.com  # Redis服务器地址
    port: 7480  # Redis服务器连接端口
    password:    # Redis服务器连接密码（默认为空）
    timeout: 0  # 连接超时时间（毫秒）